
import { Module, ValidationPipe } from '@nestjs/common'
import { GraphQLModule } from '@nestjs/graphql'
import { MercuriusDriver, MercuriusDriverConfig } from '@nestjs/mercurius'
import * as path from 'node:path'
import { UserModule } from '@e-commerce-app/api/feature-user'
import { HomeBlockModule } from '@e-commerce-app/api/feature-home-block'
import { ProductModule } from '@e-commerce-app/api/feature-product'
import { APP_PIPE } from '@nestjs/core'

const validationProvider = {
  provide: APP_PIPE,
  useValue: new ValidationPipe()
}
@Module({
  imports: [
    GraphQLModule.forRoot<MercuriusDriverConfig>({
      driver: MercuriusDriver,
      graphiql: true,
      autoSchemaFile: path.join(__dirname, './autogenerated-schema.gql')
    }),
    UserModule,
    HomeBlockModule,
    ProductModule
  ],
  providers: [validationProvider]
})
export class AppModule {}
