version: '3.9'
services:
  db:
    image: postgres
    ports:
      - '5555:5432'
    volumes:
      - db-data:/var/lib/posgresql/data
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      PGDATA: /var/lib/posgresql/data/pgdata
volumes:
  db-data: